# Generated by Django 5.1.3 on 2024-11-20 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tribunal', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('decision', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('descriptors', models.TextField(blank=True, null=True)),
                ('main_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(choices=[('CASE', 'Case'), ('LAW', 'Law')], max_length=50)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='DMSApp.document')),
            ],
        ),
    ]
