# Generated by Django 5.1.3 on 2024-11-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMSApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='process_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
